# Site settings
title: Principia de Martin
description: > # this means to ignore newlines until "baseurl:"
  Martin is a curious sole who keeps learning and checking out new
  technologies, programming languages, and much more. With an
  entrepreneurial spirit a lot creative ideas and project arises only
  to broaden his curiosity even further.
baseurl: "" # the subpath of your site, e.g. /blog/

author:
  name: Martin Jensen
  email: martin@25144754.dk
  url: "http://25144754.dk" # the base hostname & protocol for your site
  # facebook: cptactionhank
  # twitter: dotmaage
  linkedin: martinakseljensen
  instagram: cptactionhank
  github:  cptactionhank
  bitbucket: cptactionhank
  dockerhub: cptactionhank
